#!/usr/bin/env python3
# Copyright (c) 2026 James Leaver.
# SPDX-License-Identifier: MIT
# pIRCIS -- https://github.com/jamesleaver/pIRCIS
#
# Bakes the bundled example programs into flash, from programs/.
#
# These replace the examples that used to come from IRCIS-master/examples.
# Those are fine programs but they are up to 28 x 73, which on a 480 x 320
# panel means the small font and scrolling before you have understood
# anything. Everything bundled here fits 34 x 11, so the whole program is on
# screen at the large font while it runs, which is the point of the device.
#
# All of programs/ is bundled. dice never finishes -- it keeps its runners
# orbiting so the roll stays countable -- and the golden test knows that.
import os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(__file__), "..", "programs")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(__file__), "..", "lib", "program", "src", "Examples.h")

# Everything under programs/ is bundled, and the layout there is the layout on
# the device: one directory per PROG folder, and a file per program named the
# way the device names it. So the folder and the title are read off the tree
# rather than kept in a list here that has to be remembered when a program is
# added or moved. The device turns "Hello World" into Hello-World.txt; going the
# other way is the same swap, hyphens back to spaces.
# The program the device opens on, by the name it shows.
OPENING = "Motto"


def title_of(leaf):
    return leaf.replace("-", " ")


def programs_on_disk():
    out = []
    for folder in sorted(os.listdir(SRC)):
        d = os.path.join(SRC, folder)
        if not os.path.isdir(d):
            continue
        for fn in sorted(os.listdir(d)):
            if fn.endswith(".txt"):
                out.append((title_of(fn[:-4]), os.path.join(folder, fn), folder))
    return out


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

progs = []
for name, fn, folder in programs_on_disk():
    p = os.path.join(SRC, fn)
    rows = [l.rstrip("\n").rstrip("\r") for l in open(p, encoding="utf-8")]
    while rows and not rows[-1].strip():
        rows.pop()
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, ".") for r in rows]
    progs.append((name, fn, rows, w, folder))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("#pragma once\n")
    f.write("// GENERATED by tools/gen_examples.py -- do not edit by hand.\n")
    f.write("//\n")
    f.write("// The bundled programs, baked in from programs/. Nearly all are this\n")
    f.write("// project's; binary.txt is Arjun Nair's, MIT licensed and copyright\n")
    f.write("// (c) 2019 Arjun Nair -- see lib/ircis/LICENSE.\n")
    f.write("//\n")
    f.write("// Rows are padded with '.' (IRCIS blank) to a rectangle, which is what\n")
    f.write("// the interpreter's Grid expects.\n\n")
    f.write("namespace prog {\n")
    for i, (name, fn, rows, w, _d) in enumerate(progs):
        f.write("  // %s -- %d x %d\n" % (fn, len(rows), w))
        f.write("  inline const char* const kExample%d[] = {\n" % i)
        for r in rows:
            f.write('    "%s",\n' % esc(r))
        f.write("  };\n")
    f.write("\n  // folder is where the program is written on the device -- one\n")
    f.write("  // level, empty for the top of the list.\n")
    f.write("  struct ExampleDef { const char* name; const char* folder; const char* const* rows; int rows_n; int cols_n; };\n")
    f.write("  inline const ExampleDef kExamples[] = {\n")
    for i, (name, fn, rows, w, _d) in enumerate(progs):
        f.write('    { "%s", "%s", kExample%d, %d, %d },\n' % (esc(name), esc(_d), i, len(rows), w))
    f.write("  };\n")
    f.write("  inline constexpr int kExampleCount = %d;\n" % len(progs))
    # The one the device opens on. Reading the programs off the tree puts them
    # in alphabetical order, which is right for the list and wrong for the
    # first thing anybody sees, so say which one it is rather than relying on
    # whichever happens to sort first.
    opening = next((i for i, p in enumerate(progs) if p[0] == OPENING), 0)
    f.write("  inline constexpr int kOpeningExample = %d;  // %s\n"
            % (opening + 1, esc(progs[opening][0])))
    f.write("  inline constexpr int kExampleMaxRows = %d;\n" % max(len(r) for _,_,r,_,_d in progs))
    f.write("  inline constexpr int kExampleMaxCols = %d;\n" % max(w for _,_,_,w,_d in progs))
    f.write("}\n")

print("wrote %s: %d programs, largest %d x %d" % (
    OUT, len(progs), max(len(r) for _,_,r,_,_d in progs), max(w for _,_,_,w,_d in progs)))
