#!/usr/bin/env python3
# Copyright (c) 2026 James Leaver.
# SPDX-License-Identifier: MIT
# pIRCIS -- https://github.com/jamesleaver/pIRCIS
#
# Bakes the IRCIS example programs into flash. The programs themselves are
# Arjun Nair's, MIT licensed, from IRCIS-master/examples.
import os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "../IRCIS-master/examples"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(__file__), "..", "lib", "program", "src", "Examples.h")

# name shown on the device -> source file
WANTED = [
    ("Hello World",   "hello_world.txt"),
    ("Binary",        "num_to_binary_rev.txt"),
    ("Factors",       "factors.txt"),
    ("Calculator",    "calc.txt"),
    ("FizzBuzz",      "fizzbuzz.txt"),
    ("Racetrack",     "racetrack.txt"),
    ("Options",       "options.txt"),
]

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

progs = []
for name, fn in WANTED:
    p = os.path.join(SRC, fn)
    if not os.path.exists(p):
        print("  missing, skipped: %s" % p); continue
    rows = [l.rstrip("\n").rstrip("\r") for l in open(p, encoding="utf-8")]
    while rows and not rows[-1].strip():
        rows.pop()
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, ".") for r in rows]
    progs.append((name, fn, rows, w))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("#pragma once\n")
    f.write("// GENERATED by tools/gen_examples.py -- do not edit by hand.\n")
    f.write("//\n")
    f.write("// The IRCIS example programs, from IRCIS-master/examples. They are\n")
    f.write("// Arjun Nair's work, MIT licensed and copyright (c) 2019 Arjun Nair;\n")
    f.write("// see lib/ircis/LICENSE. Only the packaging is this project's.\n")
    f.write("//\n")
    f.write("// Rows are padded with '.' (IRCIS blank) to a rectangle, which is what\n")
    f.write("// the interpreter's Grid expects.\n\n")
    f.write("namespace prog {\n")
    for i, (name, fn, rows, w) in enumerate(progs):
        f.write("  // %s -- %d x %d\n" % (fn, len(rows), w))
        f.write("  inline const char* const kExample%d[] = {\n" % i)
        for r in rows:
            f.write('    "%s",\n' % esc(r))
        f.write("  };\n")
    f.write("\n  struct ExampleDef { const char* name; const char* const* rows; int rows_n; int cols_n; };\n")
    f.write("  inline const ExampleDef kExamples[] = {\n")
    for i, (name, fn, rows, w) in enumerate(progs):
        f.write('    { "%s", kExample%d, %d, %d },\n' % (esc(name), i, len(rows), w))
    f.write("  };\n")
    f.write("  inline constexpr int kExampleCount = %d;\n" % len(progs))
    f.write("  inline constexpr int kExampleMaxRows = %d;\n" % max(len(r) for _,_,r,_ in progs))
    f.write("  inline constexpr int kExampleMaxCols = %d;\n" % max(w for _,_,_,w in progs))
    f.write("}\n")

print("wrote %s: %d programs, largest %d x %d" % (
    OUT, len(progs), max(len(r) for _,_,r,_ in progs), max(w for _,_,_,w in progs)))
