#!/usr/bin/env python3
# Copyright (c) 2026 James Leaver.
# SPDX-License-Identifier: MIT
#
# Builds the content pack and writes it out as a C array.
#
#   tools/mkpack.py <word> <word> <manifest.json> [out.h]
#
# The manifest describes the sections; it lives outside this repository. The
# two words are arguments and are not written anywhere.
import hashlib, json, os, struct, sys

DELTA, M = 0x9E3779B9, 0xFFFFFFFF
MAGIC = bytes([0x70, 0x6b, 0x01, 0x1f])
VERSION = 2
SEC_GRID, SEC_SLOTS, SEC_STRINGS, SEC_PAGES, SEC_SETS = 1, 2, 3, 4, 5
GROUPS = {"info": 1, "device": 2, "splash": 3}
KINDS = {"Base64": 0, "Count": 1, "Raw": 2}

def tea_encrypt(k, blk):
    v0, v1 = struct.unpack(">II", blk)
    s = 0
    for _ in range(32):
        s = (s + DELTA) & M
        v0 = (v0 + ((((v1 << 4) & M) + k[0]) ^ ((v1 + s) & M) ^ ((v1 >> 5) + k[1]))) & M
        v1 = (v1 + ((((v0 << 4) & M) + k[2]) ^ ((v0 + s) & M) ^ ((v0 >> 5) + k[3]))) & M
    return struct.pack(">II", v0, v1)

def cbc_encrypt(key, iv, data):
    k = struct.unpack(">IIII", key)
    out, prev = b"", iv
    for i in range(0, len(data), 8):
        blk = bytes(a ^ b for a, b in zip(data[i:i+8], prev))
        prev = tea_encrypt(k, blk)
        out += prev
    return out

def derive(a, b):
    m = hashlib.sha256(hashlib.sha256(a.encode()).digest() +
                       hashlib.sha256(b.encode()).digest()).digest()
    return m[:16], m[16:24]

def s8(s):                                     # short string, u8 length
    b = s.encode("utf-8")
    if len(b) > 255: sys.exit("string too long for u8: %r" % s[:40])
    return bytes([len(b)]) + b

def s16(s):                                    # long string, u16 length
    b = s.encode("utf-8")
    if len(b) > 0xFFFF: sys.exit("string too long for u16")
    return struct.pack("<H", len(b)) + b

def section(sid, payload):
    if len(payload) > 0xFFFF:
        sys.exit("section %d is too large (%d bytes)" % (sid, len(payload)))
    return bytes([sid]) + struct.pack("<H", len(payload)) + payload

def build_grid(path):
    rows = [l.rstrip("\r\n") for l in open(path, encoding="utf-8")]
    while rows and not rows[-1].strip():
        rows.pop()
    width = max(len(r) for r in rows)
    rows = [r.ljust(width, ".") for r in rows]
    if len(rows) > 255 or width > 255:
        sys.exit("grid does not fit a byte per dimension")
    return bytes([len(rows), width]) + "".join(rows).encode("utf-8"), len(rows), width

def build_slots(slots, primary):
    if len(slots) > 255: sys.exit("too many slots")
    out = bytes([len(slots), primary])
    for s in slots:
        out += s8(s["id"]) + s8(s["label"])
        out += bytes([s["row"], s["col"], s["len"],
                      KINDS[s["kind"]], 1 if s["reversed"] else 0])
        out += s16(s["help"])
    return out

def build_strings(order, table):
    out = struct.pack("<H", len(order))
    for name in order:
        out += s16(table[name])
    return out

def build_pages(groups):
    out = bytes([len(groups)])
    for name, pages in groups.items():
        out += bytes([GROUPS[name], len(pages)])
        for p in pages:
            hl = p["highlight"]
            out += s8(p["tag"]) + struct.pack("<b", hl) + bytes([len(p["lines"])])
            for line in p["lines"]:
                out += s16(line)
    return out

def build_sets(groups):
    out = bytes([len(groups)])
    for g in groups:
        out += s8(g["head"]) + bytes([g["cells"], 1 if g["count"] else 0])
        out += bytes([len(g["slots"])]) + b"".join(s8(x) for x in g["slots"])
        out += bytes([len(g["builtin"])]) + b"".join(s16(x) for x in g["builtin"])
    return out

def main():
    if len(sys.argv) < 4:
        sys.exit("usage: mkpack.py <word> <word> <manifest.json> [out.h]")
    w1, w2, mpath = sys.argv[1], sys.argv[2], sys.argv[3]
    out = sys.argv[4] if len(sys.argv) > 4 else os.path.join(
        os.path.dirname(__file__), "..", "lib", "pack", "src", "PackData.h")

    m = json.load(open(mpath, encoding="utf-8"))
    gridpath = os.path.join(os.path.dirname(os.path.abspath(mpath)), m["grid"])

    grid, rows, cols = build_grid(gridpath)
    parts = [section(SEC_GRID,    grid),
             section(SEC_SLOTS,   build_slots(m["slots"], m["primary"])),
             section(SEC_STRINGS, build_strings(m["stringOrder"], m["strings"])),
             section(SEC_PAGES,   build_pages(m["pages"])),
             section(SEC_SETS,    build_sets(m["sets"]))]

    # magic(4) version(1) sections(1) reserved(2), then the sections themselves.
    plain = MAGIC + bytes([VERSION, len(parts), 0, 0]) + b"".join(parts)
    plain += b"\x00" * ((-len(plain)) % 8)          # TEA takes whole blocks

    key, iv = derive(w1, w2)
    blob = cbc_encrypt(key, iv, plain)

    with open(out, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// GENERATED by tools/mkpack.py -- do not edit by hand.\n")
        f.write("//\n")
        f.write("// An encrypted content pack.\n\n")
        f.write("#include <cstddef>\n#include <cstdint>\n\n")
        f.write("namespace pack {\n")
        f.write("  inline constexpr std::size_t kPackBytes = %d;\n" % len(blob))
        f.write("  inline const uint8_t kPackData[kPackBytes] = {\n")
        for i in range(0, len(blob), 12):
            f.write("    " + " ".join("0x%02x," % b for b in blob[i:i+12]) + "\n")
        f.write("  };\n}\n")
    print("wrote %s: %d bytes (%dx%d grid, %d slots, %d strings)" %
          (out, len(blob), rows, cols, len(m["slots"]), len(m["stringOrder"])))

main()
